apiVersion: v1
data:
  mapRoles:  |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::963964593909:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-ZB4AYZS5HOX4
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::963964593909:role/UdacityFlaskDeployCBKubectlRole
      username: build 
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-02T12:30:26Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "56121"
  uid: 938b580b-cd9f-40d8-b664-13ebb578a0a0
